### PR TITLE
Simplification, new syntax, better tests

### PR DESCRIPTION
**Pull request by matthias-t**
## Syntax
I've been working on a new syntax to address following problems:

### Readability 
```
subtract(divide(subtract(1.5em, 1em), 2), add(1em, 1ex))
```
Has poor readability compared to:
```
(1.5em - 1em) / 2 - (1em + 1ex)
```

### Simplification
```
subtract(1em, add(1em, 1ex))
```
Compiles to:
```
calc(1em - (1em + 1ex))
```
Which could be further simplified to:
```
1ex
```
If everything is passed to a single function, it would be easier to simplify things as much as possible, even though it wouldn't make a big difference.

### Solution
My idea was a new `math($input)` function that would take either a string or a list as input.

String syntax — better readability:
```
math( '(200px + 1px) * 2 - #{$value}' )
```
List syntax — easier and safer to code because no complicated number/unit casts are necessary:
```
math( '(' 200px '+' 1px ')' '*' 2 '-' $value )
```
I went with the latter because according to [this comment](https://github.com/sass/sass/issues/1027#issuecomment-29585132):

> Unit stripping and conversion code is harmful and can be handled simply in sass with simple arithmetic.

The quotes prevent sass from evaluating the expression as math and thus a list is passed to the `math` function. That way, it's only necessary to put quotes around operators and to call the `math` function to harness the power of CSS `calc()`.

## Tests
I've added a test function that calls any function with given arguments and checks the output. It throws a warning if the test fails, so you don't need to diff the output with a css file anymore. It also nicely prints results.

Since this worked out so well, I thought I would share this test function with others by making a small library/module. Then I could remove it from here and add it as a dependency, which would be a bit cleaner in my opinion. What do you think?

I've transcribed your tests and added tests for all functions but I don't really have experience with TDD, so tell me if the tests need improvement, or if you prefer the tests to error if they fail.

**Note:** you might wonder why the test function doesn't just take two arguments, one where you write an expression, and the other where you put the expected result. It's because otherwise you couldn't print the tested function and arguments and you couldn't read from the console what specific test has failed (just a line number) — unless you duplicate the expression into a string which would be dangerous because things like modifying the expression and not the string are likely to happen.

## Other changes
- Organised the functions into files and documented their purpose, arguments, output, and author
- Fixed `is-zero` (#1)

## Questions
- Why does `format` add `%` when there is no unit?
- Why does `add(1px, 2)` return `3px`?

## Progress
- [x] Refactor and document
- [x] Add test function
- [x] Add tests for everything
- [x] Fix `is-zero`
- [x] Change ascii art :stuck_out_tongue_winking_eye:
- [x] Add `math($list)` function
- [x] Simplification
  - [x] add `value` type
  - [x] in `math($list)`
  - [x] in `add`, `subtract`, `multiply`, `divide`
  - [ ] in `value` type, add support for square and inverse units
- [x] Extract test function to module

**PS:** This is my first contribution to open-source

### CODE REVIEW

**Comment by lunelson** [comment]
Hi @matthias-t , thanks for all of this! I'll need a bit more time before I can look at this properly (non-coding things to do, in the last days of the year); but I can comment and answer regarding some of your points above:

> Readability

You're right that `subtract(divide(subtract(1.5em, 1em), 2), add(1em, 1ex))` is a lot less readable than `(1.5em - 1em) / 2 - (1em + 1ex)`, but there's nothing preventing you from writing `calc((1.5em - 1em) / 2 - (1em + 1ex))` directly in Sass: Sass ignores the contents `calc()` expressions and passes them through as if they were strings. The aim of this library is to make it easier to work with `calc()` expressions along with normal Sass variables either for using variables inside `calc()` (where you would otherwise have to use string-interpolation syntax), or to pass `calc()` expressions in to new `calc()` expressions. The `add`, `subtract`, `multiply` and `divide` functions are more meant to be used successively to build up complex calc expressions, rather than to write them out in a single line (although one can do that). For example:

```scss
$height: 1.5em;
$trim: subtract($height, 1em); // calc(1.5em - 1em)
$half-trim: divide($trim, 2); // calc((1.5em - 1em) / 2)
```

> Simplification

The example you provide could indeed be simplified further, but it would require a lot of complexity to figure it out programatically (I think), because part of the expression is in parentheses. FWIW I have used comparison checks in these functions, to try to ensure that simple operations that can be evaluated with Sass math will just fall back to that without producing a `calc()` expression. e.g. if that example had been written differently, it would simplify itself automatically:

```scss
add(subtract(1em, 1em), 1ex); // 1ex
```

> Why does `format` add `%` when there is no unit?

The reason for this is that a unitless zero will cause a `calc()` expression to fail, at least in some browsers. It seems odd in a way, because unitless zeros are valid in CSS, but `calc()` expression require concrete values. It might be more pure perhaps, to just let the expression fail, but I felt that it was better to correct it, again because you may be producing your `calc()` expression from variables, and might have to do extensive debugging to find the value that is coming through as a unitless zero. I've chosen to assume that the intention with a unitless zero is "zero length". I've chose to add the `%` unit because that is never stripped out by CSS minifiers (although minifiers should never strip units from inside calc expressions)

> Why does `add(1px, 2)` return `3px`?

This is in keeping with Sass math: adding unit and unitless numbers in Sass produces a unit number. Similar to the above, it makes an assumption about what you intended to do.

For the rest, I'll get back to you soon. I'm very interested to read all your code, particularly how you solved the is-zero check and what you created for running tests!

**Comment by matthias-t** [comment]
>adding unit and unitless numbers in Sass produces a unit number

This may make sense for Sass because they can't add numbers with different units, but if we can use css `calc()`, then I really feel like `add(1px, 2)` should be `calc(1px + 2)` because that's how units work. `1m + 2` is not `3m`, but `1m + 2`.

**Comment by lunelson** [comment]
Right, but as with a unitless zero, a unitless number will also cause a `calc()` expression to fail. A number on its own is meaningless to the browser in that context. And it would go against Sass convention and the expectations of anyone using this code, to do so. Consider the following, with Sass' built-in `comparable()` function, which I use for the simplification checks—Sass considers these quantities comparable and operable:

```scss
.test {
  out: 1px + 2;
  out: comparable(1px, 2);
}
```
```css
.test {
  out: 3px;
  out: true;
}
```

**Comment by matthias-t** [comment]
I agree, but is there a use case for for `add(1px, 2)` other than having forgotten a unit? If it should return `3px` at least we should warn the user he has probably just forgot a unit and will get an unexpected result.

And how is `1px + 2 == 3px` a Sass convention and not a side-effect or a similar problem to [this](https://github.com/sass/sass/issues/1496). To cite this same issue: 

>In CSS the actual unit or lack of unit is very important. I can't think of any real use-case where I would be equally happy with or without a unit.

**Comment by lunelson** [comment]
So, I've finally got a chance to look through this, there's a lot going on so I'm trying to pull it apart. 

Firstly, to respond to your comment above: I wasn't aware of the issue you linked to, and I don't really have an opinion about whether that behaviour should be changed but if and when it does change, the behavior of the built-in `comparable()` function will also change, so as a library author the best policy is to rely on that function. As for use-cases: there are properties in CSS which can accept unit or unitless numbers, but there is no use-case for a mix of unit and unitless, and while `calc()` expressions can mix units, any unitless number in a `calc()` expression will cause the expression to fail, as I mentioned. As for the Sass use-case of this operation: you are making use of it yourself, in your `get-units` function:

```scss
@function get-units($value) {
  $units: ();
  @each $number in $value {
    $unit: get-unit($number);
    $units: append($units, $unit, space);
  }
  @return $units;
}
```

Without the fact that e.g. `0px + 1 == 1px`, this function will not work. It's the most common way to strip units in Sass but I do it this way, which will still work if/when the behaviour of Sass changes WRT unit/unitless operations:

```scss
@function one($unit:'') {
  $one: ('em': 1em, 'ex': 1ex, 'ch': 1ch, 'rem': 1rem, '%': 1%, 'vw': 1vw, 'vh': 1vh, 'vmin': 1vmin, 'vmax': 1vmax, 'cm': 1cm, 'mm': 1mm, 'in': 1in, 'px': 1px, 'pt': 1pt, 'pc': 1pc, 'deg': 1deg, 'grad': 1grad, 'rad': 1rad, 'turn': 1turn, 's': 1s, 'ms': 1ms, 'dpi': 1dpi, 'dpcm': 1dpcm, 'dppx': 1dppx);
  @return map-get($one, $unit) or 1;
}

@function strip($n) {
  @if not is-number($n) { @return error("cannot manipulate unit of non-number"); }
  @return if(unitless($n), $n, $n / one(unit($n)));
}
```

**Comment by lunelson** [comment]
As for your testing functions, I like the approach. However, it's only for testing functions if I understand correctly? The `gulp-diff`-based approach I use requires a bit more attention and work but it does allow testing all parts of the code 🤷‍♂️

**Comment by lunelson** [comment]
@matthias-t a few additions:

1. I got an answer back on that other issue, as you might have seen: the actual math behaviour of adding and subtracting unit and unitless numbers is not going to change, even though `2 == 2px` will return `false`.

2. for the record, I think you should publish a package for your testing approach, it would be cool.

3. I'm intrigued by the `value` code you wrote and how it works but I find it hard to trace; I wonder if you could make a Sassmeister pen that would walk me through it?

**Comment by matthias-t** [comment]
Hi @lunelson!

First of all, thanks a lot for taking the time to look at my code and ask for clarifications on the issue I referenced.

Regarding your comments:

- You're right about the tests, it only works for functions. I could add something like `assert(1 + 2px, 3px)`  , but it wont be possible to print `1 + 2px ==> 3px (expected)` to the console, because Sass will evaluate it before passing it as an argument. Accepting a string instead is not an option because Sass [does not](https://stackoverflow.com/questions/29810212/can-sass-evaluate-strings-that-contain-mathematical-expressions) have an `eval($string)` function.

- In its current state, `value` does not support square / inverse units so you cannot `divide(5px, 3em)`. I am currently making changes to how it works to support this kind of operation (almost done). 

- Once I'm done with that, I'll be glad to make a Sassmeister pen to explain it in detail. Also, if you're in Berlin, you could join me at [this meetup](https://www.meetup.com/opentechschool-berlin/events/243485867/) so I can explain the code to you personally and we can discuss the changes.

**Comment by lunelson** [comment]
Hey @matthias-t that's a great idea, about the Co-Learning meetup—I've been meaning to go to one of those for a long time. I've registered and I'll aim to be there around 19:45, we can discuss this then!

**Pull request closed without merging**
